[project]
name = "suurennuslasi-api"
version = "0.1.0"
description = ""
authors = [
    {name = "nicolasspring",email = "springn.ch@gmail.com"}
]
requires-python = ">=3.12"
dynamic = [ "dependencies" ]

[tool.poetry.dependencies]
fastapi = "^0.136.3"
uvicorn = "^0.48.0"
greenlet = "^3.5.1"
python-multipart = "^0.0.29"
asyncpg = "^0.31.0"
suurennuslasi-db = { path = "../../packages/db", develop = true }
suurennuslasi-domain = { path = "../../packages/domain", develop = true }
suurennuslasi-storage = { path = "../../packages/storage", develop = true }

[tool.poetry.group.dev.dependencies]
black = "^26.5.1"
isort = "^8.0.1"
pytest = "^9.0.3"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'SERVICES', 'PACKAGES', 'FIRSTPARTY', 'LOCALFOLDER']
known_services = ["suurennuslasi_api"]
known_packages = ["suurennuslasi_db", "suurennuslasi_domain", "suurennuslasi_events", "suurennuslasi_storage"]
